units:
  mcu_w: 15
  mcu_h: 20
  mcu_p: 2

  # trrs_w: 13

  p: u+3

points:
  zones:
    matrix:
      rows:
        bottom:
          # ROW3
          row_net: l_A2
          mirror.row_net: r_A8
        home:
          # ROW2
          row_net: l_A1
          mirror.row_net: r_A9
        top:
          # ROW1
          row_net: l_A0
          mirror.row_net: r_A10
      columns:
        pinky:
          # COL1
          key:
            column_net: l_A10
            mirror.column_net: r_A0
        ring:
          # COL2
          key:
            column_net: l_A9
            mirror.column_net: r_A1
            origin: [-12, -u]
            stagger: 10
            splay: -4
        middle:
          # COL3
          key:
            column_net: l_A8
            mirror.column_net: r_A2
            stagger: 5
        index:
          # COL4
          key:
            column_net: l_A7
            mirror.column_net: r_A3
            stagger: -5
        inner:
          # COL5
          key:
            column_net: l_A4
            mirror.column_net: r_A4
            stagger: -2
      anchor:
        shift: [100, -150]
        rotate: 4
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        shift: [0, -25]
        rotate: -15
      columns:
        near:
          #COL3
          key:
            column_net: l_A8
            mirror.column_net: r_A2
        home:
          #COL4
          key:
            column_net: l_A7
            mirror.column_net: r_A3
            spread: U
            splay: -15
            origin: [-10, -9]
        far:
          #COL5
          key:
            column_net: l_A4
            mirror.column_net: r_A4
            spread: U
            splay: -15
            origin: [-10, -9]
      rows:
        thumb:
          #ROW4
          row_net: l_A3
          mirror.row_net: r_A7
  rotate: 0
  mirror: &mirror
    ref: thumbfan_far_thumb
    distance: 34
outlines:
  keys:
    - what: rectangle
      where: true
      size: [14, 14]
  demo:
    - what: rectangle
      where: true
      size: [u-1, u-1]
    - what: rectangle
      where: true
      size: [13.5, 13.5]
      operation: stack
  out:
    - what: polygon
      operation: add
      fillet: 2
      points:
        - ref: thumbfan_near_thumb
          shift: [-0.5p, -0.5p]
        - ref: matrix_pinky_bottom
          shift: [2p+mcu_p-2.5, -0.5p]
        - ref: matrix_pinky_bottom
          shift: [-0.5p, -0.5p]
        - ref: matrix_pinky_top
          shift: [-0.5p, 0.5p]
        - ref: matrix_pinky_top
          shift: [0.5p+1, 0.5p]
        - ref: matrix_ring_top
          shift: [-0.5p, 0.5p]
        - ref: matrix_ring_top
          shift: [0.5p, 0.5p]
        - ref: matrix_index_top
          shift: [0.5p, 0.5p]
        - ref: matrix_inner_top
          shift: [-0.5p+3, 0.5p+2]
        - ref: matrix_inner_top
          shift: [0.5p+mcu_p+mcu_p+mcu_w, 0.5p+2]
        - ref: matrix_inner_top
          shift: [0.5p+mcu_p+mcu_p+mcu_w, 0.5p-mcu_h-mcu_p+2]
        - ref: matrix_inner_top
          shift: [0.5p+mcu_w+mcu_p+mcu_p-10.5, 0.5p-mcu_h-mcu_p+2-7]
        - ref: matrix_inner_top
          shift: [0.5p+mcu_w+mcu_p+mcu_p-10.5, 0.5p-mcu_h-mcu_p-mcu_p-18]
        - ref: matrix_inner_top
          shift: [0, 0.5p-mcu_h-mcu_p-mcu_p-18-8]
        - ref: thumbfan_far_thumb
          shift: [-1p, 0.5p]
        - ref: thumbfan_far_thumb
          shift: [0.5p, 0.5p]
        - ref: thumbfan_far_thumb
          shift: [0.5p, -0.5p]
        - ref: thumbfan_far_thumb
          shift: [-0.5p, -0.5p]
        - ref: thumbfan_home_thumb
          shift: [-0.5p, -0.5p]
    - what: rectangle
      where: matrix_inner_bottom
      size: [p, 2.5p]
      fillet: 5
      operation: add
    - what: rectangle
      where: matrix_middle_top
      size: [p, p]
      fillet: 2
      operation: add
    # mirror
    - what: polygon
      operation: add
      fillet: 2
      points:
        - ref: mirror_thumbfan_near_thumb
          shift: [-0.5p, -0.5p]
        - ref: mirror_matrix_pinky_bottom
          shift: [2p+mcu_p-2.5, -0.5p]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5p, -0.5p]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5p, 0.5p]
        - ref: mirror_matrix_pinky_top
          shift: [0.5p+1, 0.5p]
        - ref: mirror_matrix_ring_top
          shift: [-0.5p, 0.5p]
        - ref: mirror_matrix_ring_top
          shift: [0.5p, 0.5p]
        - ref: mirror_matrix_index_top
          shift: [0.5p, 0.5p]
        - ref: mirror_matrix_inner_top
          shift: [-0.5p+3, 0.5p+2]
        - ref: mirror_matrix_inner_top
          shift: [0.5p+mcu_p+mcu_p+mcu_w, 0.5p+2]
        - ref: mirror_matrix_inner_top
          shift: [0.5p+mcu_p+mcu_p+mcu_w, 0.5p-mcu_h-mcu_p+2]
        - ref: mirror_matrix_inner_top
          shift: [0.5p+mcu_w+mcu_p+mcu_p-10.5, 0.5p-mcu_h-mcu_p+2-7]
        - ref: mirror_matrix_inner_top
          shift: [0.5p+mcu_w+mcu_p+mcu_p-10.5, 0.5p-mcu_h-mcu_p-mcu_p-18]
        - ref: mirror_matrix_inner_top
          shift: [0, 0.5p-mcu_h-mcu_p-mcu_p-18-8]
        - ref: mirror_thumbfan_far_thumb
          shift: [-1p, 0.5p]
        - ref: mirror_thumbfan_far_thumb
          shift: [0.5p, 0.5p]
        - ref: mirror_thumbfan_far_thumb
          shift: [0.5p, -0.5p]
        - ref: mirror_thumbfan_far_thumb
          shift: [-0.5p, -0.5p]
        - ref: mirror_thumbfan_home_thumb
          shift: [-0.5p, -0.5p]
    - what: rectangle
      where: mirror_matrix_inner_bottom
      size: [p, 2.5p]
      fillet: 5
      operation: add
    - what: rectangle
      where: mirror_matrix_middle_top
      size: [p, p]
      fillet: 2
      operation: add
      # check key placing
    # - what: outline
    #   name: demo
    #   operation: stack
  plate:
    - what: outline
      name: out
      operation: add
    - what: outline
      name: keys
      operation: subtract
  pcb_plate:
    - what: outline
      name: out
      operation: add
    - what: circle
      where:
        ref: [matrix_index_bottom]
        shift: [10, 0]
      radius: 1
      operation: subtract
pcbs:
  ergojodi:
    outlines:
      main:
        outline: pcb_plate
    footprints:
      mx_hotswap:
        what: mx_new
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      xiao_left:
        what: xiao
        params:
          side: B
          A0: l_A0
          A1: l_A1
          A10: l_A10
          A2: l_A2
          A3: l_A3
          A4: l_A4
          A5: l_A5
          A6: l_Dplus #l_A6
          A7: l_A7
          A8: l_A8
          A9: l_A9
          GND: l_GND
          P_3V3: l_P_3V3
          VCC: l_VCC
        where:
          ref: matrix_inner_top
          shift: [mcu_p+mcu_w+mcu_p, mcu_p+0.5]
          rotate: 0
      # trrs_left:
      #   params:
      #     side: B
      #     TP: "l_TP"
      #     R1: "l_R1"
      #     R2: "l_R2"
      #     SL: "l_SL"
      #   what: trrs_pj320a
      #   where:
      #     ref: matrix_inner_home
      #     shift: [trrs_w+9, -1.8mcu_p]
      #     rotate: -90
      # trrs_right:
      #   params:
      #     side: B
      #     TP: "r_TP"
      #     R1: "r_R1"
      #     R2: "r_R2"
      #     SL: "r_SL"
      #   what: trrs_pj320a
      #   where:
      #     ref: mirror_matrix_inner_home
      #     shift: [trrs_w+9, -1.8mcu_p]
      #     rotate: -90
      usbc_left:
        what: usbc
        params:
          side: F
          A1: l_GND
          A12: l_GND
          A4: l_VCC
          A5: l_A5u
          A6: l_Dplus
          A7: l_Dminus
          A8: l_A8u
          A9: l_VCC
          B1: l_GND
          B12: l_GND
          B4: l_VCC
          B5: l_B5u
          B6: l_Dplus
          B7: l_Dminus
          B8: l_B8u
          B9: l_VCC
          NP: l_GND
        where:
          ref: matrix_inner_home
          shift: [17, -2.2mcu_p]
          rotate: 90
      usbc_right:
        what: usbc
        params:
          side: F
          A1: r_GND
          A12: r_GND
          A4: r_VCC
          A5: r_A5u
          A6: r_Dplus
          A7: r_Dminus
          A8: r_A8u
          A9: r_VCC
          B1: r_GND
          B12: r_GND
          B4: r_VCC
          B5: r_B5u
          B6: r_Dplus
          B7: r_Dminus
          B8: r_B8u
          B9: r_VCC
          NP: r_GND
        where:
          ref: mirror_matrix_inner_home
          shift: [17, -2.2mcu_p]
          rotate: 90
      xiao_right:
        what: xiao
        params:
          side: B
          A0: r_A0
          A1: r_A1
          A10: r_A10
          A2: r_A2
          A3: r_A3
          A4: r_A4
          A5: r_A5
          A6: r_Dplus #r_A6
          A7: r_A7
          A8: r_A8
          A9: r_A9
          GND: r_GND
          P_3V3: r_P_3V3
          VCC: r_VCC
        where:
          ref: mirror_matrix_inner_top
          shift: [mcu_p+mcu_w+mcu_p, mcu_p+0.5]
          rotate: 0
